# Generated by Django 4.2 on 2023-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_position_remove_event_description_remove_event_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='activity_name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
